package main

import (
	"context"
	"fmt"
	spotifyauth "github.com/zmb3/spotify/v2/auth"
	"log"
	"net/http"

	"github.com/zmb3/spotify/v2"
)

const redirectURI = "http://localhost:8080/callback"

var (
	auth = spotifyauth.New(
		spotifyauth.WithRedirectURL(redirectURI),
		spotifyauth.WithScopes(spotifyauth.ScopePlaylistModifyPrivate, spotifyauth.ScopePlaylistModifyPublic),
	)
	ch    = make(chan *spotify.Client)
	state = "abc123"
)

func main() {
	var client *spotify.Client

	http.HandleFunc("/callback", completeAuth)

	go func() {
		url := auth.AuthURL(state)
		fmt.Println("Please log in to Spotify by visiting the following page in your browser:", url)

		// wait for auth to complete
		client = <-ch

		// use the client to make calls that require authorization
		user, err := client.CurrentUser(context.Background())
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println("You are logged in as:", user.ID)
		ctx := context.Background()
		playlistId := spotify.ID("06kZdWHb9ysIAn2GdFLUeC")
		//client.GetPlaylist(ctx, id)
		playlist := getPlaylist(ctx, client, playlistId)
		fmt.Println("Playlist retrieved:", playlist)
		tracks := getSimpleTracksFromPlaylist(ctx, client, playlist)
		fmt.Println("Tracks retrieved:", tracks)

		//Hardcode sample album ID
		albumId := spotify.ID("0UK9cg0SGJmRXIvSAYkl70")
		album := getAlbum(ctx, client, albumId)
		fmt.Println("Album retrieved:", album)

		//Create playlist
		createPlaylist(ctx, client, user, tracks)

	}()

	http.ListenAndServe(":8080", nil)

}

func completeAuth(w http.ResponseWriter, r *http.Request) {
	tok, err := auth.Token(r.Context(), state, r)
	if err != nil {
		http.Error(w, "Couldn't get token", http.StatusForbidden)
		log.Fatal(err)
	}
	if st := r.FormValue("state"); st != state {
		http.NotFound(w, r)
		log.Fatalf("State mismatch: %s != %s\n", st, state)
	}
	// use the token to get an authenticated client
	client := spotify.New(auth.Client(r.Context(), tok))
	w.Header().Set("Content-Type", "text/html")
	fmt.Fprintf(w, "Login Completed!")
	ch <- client
}

func getPlaylist(ctx context.Context, client *spotify.Client, playlistId spotify.ID) *spotify.FullPlaylist {
	fmt.Println("Beginning getPlaylist")

	playlist, err := client.GetPlaylist(ctx, playlistId)

	if err != nil {
		fmt.Println(err.Error)
	}
	fmt.Println(playlist.ID)
	return playlist
}

func getSimpleTracksFromPlaylist(ctx context.Context, client *spotify.Client, playlist *spotify.FullPlaylist) []spotify.SimpleTrack {
	fmt.Println("Beginning getSimpleTracksFromPlaylist")
	tracks := []spotify.SimpleTrack{}
	playlistTracks := playlist.Tracks.Tracks
	for _, playlistTrack := range playlistTracks {
		tracks = append(tracks, playlistTrack.Track.SimpleTrack)

	}
	return tracks
}

func getAlbum(ctx context.Context, client *spotify.Client, albumId spotify.ID) *spotify.FullAlbum {
	fmt.Println("Beginning getAlbum")
	album, err := client.GetAlbum(ctx, albumId)

	if err != nil {
		fmt.Println(err.Error)
	}
	fmt.Println(album.ID)
	return album
}

func createPlaylist(ctx context.Context, client *spotify.Client, user *spotify.PrivateUser, tracks []spotify.SimpleTrack) {
	fmt.Println("Beginning createPlaylist")

	playlistName := "AutogeneratedPlaylist"
	playlistDescription := "Created automatically"
	createPublicPlaylist := false
	collaborativePlaylist := false
	userId := user.ID

	createdPlaylist, err := client.CreatePlaylistForUser(ctx, userId, playlistName, playlistDescription, createPublicPlaylist, collaborativePlaylist)
	if err != nil {
		fmt.Println(err.Error)
	}
	playlistId := createdPlaylist.ID
	//Get track IDs from list of tracks
	var trackIds []spotify.ID
	for _, track := range tracks {
		trackIds = append(trackIds, track.ID)
	}
	_, err = client.AddTracksToPlaylist(ctx, playlistId, trackIds...)
	if err != nil {
		fmt.Println(err.Error)
	}

}
